### ISSUE TITLE
Merge registrazione SPID/email

### ISSUE THREAD

**Issue by mfortini** [dipartimentofunzionepubblica/partecipa#9]
Registrandosi con SPID, viene richiesto un indirizzo email. Quando questo indirizzo è già stato utilizzato per registrarsi alla piattaforma, si ha un errore.

Sarebbe invece opportuno poter fare il merge delle due utenze, come accade in altri siti.

**Comment by Jeanluc74** [comment]
Buongiorno mfortini, nella piattaforma Decidim la email utente deve essere univoca by design, non ci risulta una possibilità di modificare questo aspetto senza stravolgere la modellazione degli account utente. Puoi farci sapere in quali siti hai riscontrato la funzionalità di merge tra account Spid? Sarebbe utile per capire meglio se applicabile.
